name: Bug Report
description: For reporting bugs and other issues with RMCP
body:
  - type: textarea
  id: description
  attributes:
    label: Bug Description
    description: >-
      Use this section to describe the bug in as much detail as possible
  - type: textarea
  id: rmcp_version
  attributes:
    label: RetroMCP version
    description: >-
      v1.0
  - type: textarea
  id: mc_version
  attributes:
    label: Minecraft version
    description: >-
      b1.7.3
  - type: textarea
  id: other_description
  attributes:
    label: Other
    description: >-
      Post logs here